### ISSUE TITLE
Check for overrides when changing php settings

### ISSUE THREAD

**Issue by Derroylo** [Derroylo/gitpod-tool#76]
Using this config as a base:
```
php:
  version: 8.0
  config:
    opcache.enable: off
    xdebug.mode: off
    xdebug.start_with_request: yes
  configWeb:
    memory_limit: 512M
    xdebug.mode: off
  configCLI:
    max_execution_time: 0
    xdebug.mode: off
```

When trying to change the setting for `max_execution_time` for both cli and web, the setting will be added to `config` but will not change the value for `configCLI`. If i want to change a setting globally and there is an override in Web or CLI, then the tool should inform the user about this and aks if the override should be removed.
